OLED_ENABLE = yes
ENCODER_ENABLE = yes
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = yes
UNICODEMAP_ENABLE = yes
LTO_ENABLE = yes

WPM_ENABLE = yes

MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
MUSIC_ENABLE = no
